"""CRF (Conditional Random Fields) refinement module for heatmap post-processing.

This module provides efficient CRF-based smoothing and spatial consistency
refinement for heatmaps generated by GradCAM, Attention Rollout, and other
visualization methods.

Based on:
- https://github.com/tomgoldstein/fast-CRF
- Dense CRF implementation for image labeling
"""

from typing import Optional

import cv2
import numpy as np


class CRFRefiner:
    """Refines heatmaps using Conditional Random Fields for spatial smoothness.

    Applies CRF-based refinement to maintain spatial consistency while preserving
    object boundaries in attention heatmaps and gradient-based visualizations.
    """

    def __init__(
        self,
        iterations: int = 10,
        theta_xy: float = 80.0,
        theta_alpha: float = 0.1,
        w1: float = 10.0,
        w2: float = 3.0,
        sigma_x: float = 3.0,
        sigma_y: float = 3.0,
        sigma_rgb: float = 13.0
    ):
        """Initialize CRF refiner with specified parameters.

        Args:
            iterations: Number of CRF iterations (higher = more refinement, slower).
            theta_xy: Spatial smoothness weight (higher = more spatial smoothing).
            theta_alpha: Regularization for spatial kernel.
            w1: Weight for spatial kernel (bilateral).
            w2: Weight for color kernel (Gaussian).
            sigma_x: Spatial kernel std dev in x direction.
            sigma_y: Spatial kernel std dev in y direction.
            sigma_rgb: Color kernel std dev in RGB space.
        """
        self.iterations = iterations
        self.theta_xy = theta_xy
        self.theta_alpha = theta_alpha
        self.w1 = w1
        self.w2 = w2
        self.sigma_x = sigma_x
        self.sigma_y = sigma_y
        self.sigma_rgb = sigma_rgb

    @staticmethod
    def from_config(config_dict: Optional[dict] = None) -> 'CRFRefiner':
        """Create CRF refiner from configuration dictionary.

        Args:
            config_dict: Dictionary containing CRF parameters. If None, uses defaults.

        Returns:
            CRFRefiner instance with parameters from config or defaults.
        """
        if config_dict is None:
            config_dict = {}

        return CRFRefiner(
            iterations=config_dict.get('iterations', 10),
            theta_xy=config_dict.get('theta_xy', 80.0),
            theta_alpha=config_dict.get('theta_alpha', 0.1),
            w1=config_dict.get('w1', 10.0),
            w2=config_dict.get('w2', 3.0),
            sigma_x=config_dict.get('sigma_x', 3.0),
            sigma_y=config_dict.get('sigma_y', 3.0),
            sigma_rgb=config_dict.get('sigma_rgb', 13.0)
        )

    def refine(
        self,
        heatmap: np.ndarray,
        image: Optional[np.ndarray] = None,
        keep_peaks: bool = True
    ) -> np.ndarray:
        """Refine heatmap using simplified CRF with energy minimization.

        Uses iterative refinement by applying bilateral filtering with
        the original heatmap as guidance, gradually smoothing while
        preserving the original intensity structure.

        Args:
            heatmap: Input heatmap (H, W) normalized to [0, 1].
            image: Original image (H, W, 3) in BGR or RGB, used for color consistency.
                   If None, only spatial smoothing is applied.
            keep_peaks: If True, blend refined with original to preserve structure.

        Returns:
            Refined heatmap (H, W) normalized to [0, 1].
        """
        H, W = heatmap.shape
        heatmap = np.clip(heatmap, 0, 1).astype(np.float32)

        original = heatmap.copy()
        refined = heatmap.copy()

        for iteration in range(self.iterations):
            refined_uint8 = (refined * 255).astype(np.uint8)

            filtered = cv2.bilateralFilter(
                refined_uint8,
                d=9,
                sigmaColor=self.sigma_rgb,
                sigmaSpace=max(self.sigma_x, self.sigma_y)
            ).astype(np.float32) / 255.0

            blend_factor = 0.7 + (iteration / self.iterations) * 0.2
            refined = blend_factor * filtered + (1 - blend_factor) * original

        if keep_peaks:
            peak_threshold = 0.7
            peak_mask = original > peak_threshold
            refined[peak_mask] = 0.8 * original[peak_mask] + 0.2 * refined[peak_mask]

        refined = np.clip(refined, 0, 1).astype(np.float32)
        return refined

    def _compute_spatial_messages(
        self,
        Q: np.ndarray,
        H: int,
        W: int
    ) -> np.ndarray:
        """Compute spatial pairwise potentials using bilateral filtering.

        Args:
            Q: Probability map (2, H*W).
            H: Height of the spatial grid.
            W: Width of the spatial grid.

        Returns:
            Messages array with shape (2, H*W).
        """
        Q_spatial = Q[1, :].reshape(H, W)

        filtered = cv2.bilateralFilter(
            (Q_spatial * 255).astype(np.uint8),
            d=-1,
            sigmaColor=self.sigma_rgb,
            sigmaSpace=max(self.sigma_x, self.sigma_y)
        ).astype(np.float32) / 255.0

        msg_fg = self.w1 * (Q_spatial - filtered).flatten()
        msg_bg = -msg_fg

        messages = np.stack([msg_bg, msg_fg], axis=0)
        return messages

    def _compute_color_messages(
        self,
        Q: np.ndarray,
        image: np.ndarray,
        H: int,
        W: int
    ) -> np.ndarray:
        """Compute color pairwise potentials for consistency with image.

        Args:
            Q: Probability map (2, H*W).
            image: Original image (H, W, 3).
            H: Height of the spatial grid.
            W: Width of the spatial grid.

        Returns:
            Messages array with shape (2, H*W).
        """
        if image.dtype == np.uint8:
            image_norm = image.astype(np.float32) / 255.0
        else:
            image_norm = np.clip(image, 0, 1).astype(np.float32)

        image_lab = cv2.cvtColor(
            (image_norm * 255).astype(np.uint8),
            cv2.COLOR_RGB2LAB if image.shape[2] == 3 else cv2.COLOR_GRAY2LAB
        ).astype(np.float32) / 255.0

        Q_spatial = Q[1, :].reshape(H, W)
        fg_mask = Q_spatial > 0.5

        if fg_mask.sum() > 0:
            fg_color = image_lab[fg_mask].mean(axis=0)
            color_dist = np.linalg.norm(
                image_lab - fg_color[np.newaxis, np.newaxis, :],
                axis=2
            )
        else:
            color_dist = np.zeros((H, W))

        color_pairwise = np.exp(
            -(color_dist ** 2) / (2 * self.sigma_rgb ** 2)
        )

        msg_fg = self.w2 * (color_pairwise.flatten() - Q_spatial.flatten())
        msg_bg = -msg_fg

        messages = np.stack([msg_bg, msg_fg], axis=0)
        return messages

    def refine_simple(
        self,
        heatmap: np.ndarray,
        kernel_size: int = 5,
        sigma: float = 1.0
    ) -> np.ndarray:
        """Apply simple Gaussian blur refinement as fast alternative to full CRF.

        Args:
            heatmap: Input heatmap (H, W).
            kernel_size: Gaussian kernel size (must be odd).
            sigma: Gaussian standard deviation.

        Returns:
            Refined heatmap (H, W) normalized to [0, 1].
        """
        heatmap = np.clip(heatmap, 0, 1).astype(np.float32)

        refined = cv2.GaussianBlur(
            heatmap,
            ksize=(kernel_size, kernel_size),
            sigmaX=sigma,
            sigmaY=sigma
        )

        return np.clip(refined, 0, 1).astype(np.float32)


def refine_heatmap(
    heatmap: np.ndarray,
    image: Optional[np.ndarray] = None,
    method: str = "crf",
    **kwargs
) -> np.ndarray:
    """High-level API for heatmap refinement.

    Args:
        heatmap: Input heatmap (H, W) normalized to [0, 1].
        image: Original image for color consistency (optional).
        method: Refinement method ("crf" or "blur").
        **kwargs: Method-specific parameters.

    Returns:
        Refined heatmap (H, W) normalized to [0, 1].

    Raises:
        ValueError: If unknown refinement method is specified.
    """
    if method == "crf":
        refiner = CRFRefiner(**kwargs)
        return refiner.refine(heatmap, image=image)
    elif method == "blur":
        refiner = CRFRefiner()
        kernel_size = kwargs.get('kernel_size', 5)
        sigma = kwargs.get('sigma', 1.0)
        return refiner.refine_simple(heatmap, kernel_size=kernel_size, sigma=sigma)
    else:
        raise ValueError(f"Unknown refinement method: {method}")
