#!/usr/bin/env python3
"""
Converts LabelMe JSON files to COCO format (annotations.json).

Usage:
    python utils/convert.py data_fire/Test/annotations
    python utils/convert.py data_fire/Test/annotations -o output.json
"""

import os
import json
import shutil
import argparse

from labelme2coco import convert


# =============================================================================
# Conversion
# =============================================================================

def fix_coco_format(json_path: str):
    """
    Fix annotations.json generated by labelme2coco:
    1. file_names: only basename (without full path)
    2. category_id: 1-indexed
    """
    with open(json_path, 'r') as f:
        data = json.load(f)

    for img in data['images']:
        img['file_name'] = os.path.basename(img['file_name'])

    for cat in data.get('categories', []):
        cat['id'] = cat['id'] + 1

    for ann in data.get('annotations', []):
        ann['category_id'] = ann['category_id'] + 1

    with open(json_path, 'w') as f:
        json.dump(data, f, indent=2)


def convert_labelme_to_coco(input_dir: str, output_file: str = None):
    """
    Convert LabelMe JSON files to COCO format.

    Args:
        input_dir: Directory containing LabelMe .json files
        output_file: Output file path (default: annotations.json in parent)
    """
    if not os.path.isdir(input_dir):
        print(f"Error: '{input_dir}' is not a valid directory")
        return

    if output_file is None:
        parent_dir = os.path.dirname(os.path.abspath(input_dir))
        output_file = os.path.join(parent_dir, "annotations.json")

    print(f"Input:  {input_dir}")
    print(f"Output: {output_file}")

    temp_dir = output_file + "_temp"
    convert(input_dir, temp_dir)

    temp_json = os.path.join(temp_dir, "dataset.json")
    if os.path.exists(temp_json):
        shutil.move(temp_json, output_file)
        shutil.rmtree(temp_dir)

    fix_coco_format(output_file)
    print("Conversion complete!")


# =============================================================================
# Main
# =============================================================================

def main():
    parser = argparse.ArgumentParser(description="Convert LabelMe JSON to COCO format")
    parser.add_argument("input_dir", type=str, help="Directory containing LabelMe .json files")
    parser.add_argument("-o", "--output", type=str, default=None, help="Output file")

    args = parser.parse_args()
    convert_labelme_to_coco(args.input_dir, args.output)


if __name__ == "__main__":
    main()
